import { computeShannonEntropy } from '../src/algorithms/tools/entropy-csprng/shannon';
import { computeChiSquareTest } from '../src/algorithms/tools/entropy-csprng/chi-square';
import { generateCsprngBytes } from '../src/algorithms/tools/entropy-csprng/csprng';
import { computePasswordEntropy } from '../src/algorithms/tools/entropy-csprng/password';
import { ENTROPY_PRESETS } from '../src/algorithms/tools/entropy-csprng/presets';

console.log('=== CRYPTOSCOPE ENTROPY & CSPRNG TOOLS AUDIT ===\n');

// ---------------------------------------------------------------------------
// 1. DETERMINISTIC ZERO ENTROPY TEST
// ---------------------------------------------------------------------------
console.log('--- 1. Deterministic Zero Entropy Test (1024x 0x00) ---');
const zeroStream = new Uint8Array(1024).fill(0x00);
const zeroShannon = computeShannonEntropy(zeroStream);
const zeroChi = computeChiSquareTest(zeroStream);

console.log('Shannon Entropy H        :', zeroShannon.shannonEntropy.toFixed(4), '/ 8.0000 bits/byte');
console.log('Unique Byte Symbols      :', zeroShannon.uniqueBytes, '/ 256');
console.log('Compression Potential    :', zeroShannon.theoreticalCompressionRatio, '%');
console.log('Chi-Square Statistic χ²  :', zeroChi.chiSquareStat);
console.log('Degrees of Freedom ν     :', zeroChi.degreesOfFreedom);
console.log('Chi-Square p-value       :', zeroChi.pValue.toFixed(6));
console.log('NIST SP 800-22 Verdict   :', zeroChi.verdictMessage);
console.log('Zero Entropy Test Match  :', zeroShannon.shannonEntropy === 0.0 && zeroChi.verdict === 'non-uniform' ? 'PASS (100%)' : 'FAIL');

// ---------------------------------------------------------------------------
// 2. DETERMINISTIC UNIFORM PERMUTATION TEST (4x 0..255, N=1024)
// ---------------------------------------------------------------------------
console.log('\n--- 2. Deterministic Uniform Permutation Test (4x 0..255, N=1024) ---');
const uniformBytes = new Uint8Array(1024);
for (let c = 0; c < 4; c++) {
  for (let b = 0; b < 256; b++) {
    uniformBytes[c * 256 + b] = b;
  }
}
const uniformShannon = computeShannonEntropy(uniformBytes);
const uniformChi = computeChiSquareTest(uniformBytes);

console.log('Shannon Entropy H        :', uniformShannon.shannonEntropy.toFixed(4), '/ 8.0000 bits/byte (Maximal)');
console.log('Unique Byte Symbols      :', uniformShannon.uniqueBytes, '/ 256');
console.log('Chi-Square Statistic χ²  :', uniformChi.chiSquareStat, '(Expected 0.0)');
console.log('Chi-Square p-value       :', uniformChi.pValue.toFixed(6), '(Expected 1.0)');
console.log('NIST SP 800-22 Verdict   :', uniformChi.verdictMessage);
console.log('Uniform Permutation Match:', uniformShannon.shannonEntropy === 8.0 && uniformChi.verdict === 'too-flat' ? 'PASS (100%)' : 'FAIL');

// ---------------------------------------------------------------------------
// 3. CSPRNG LIVE GENERATION (256 & 1024 BYTES)
// ---------------------------------------------------------------------------
console.log('\n--- 3. CSPRNG Live Generation Audit (crypto.getRandomValues) ---');
const csprngSample = generateCsprngBytes(1024);
console.log('Entropy Source           :', csprngSample.entropySource);
console.log('Generated Byte Length    :', csprngSample.byteLength, 'bytes');
console.log('Shannon Entropy H        :', csprngSample.shannon.shannonEntropy.toFixed(4), '/ 8.0000 bits/byte');
console.log('Information Density      :', csprngSample.shannon.entropyRatioPercent, '%');
console.log('Unique Symbols Observed  :', csprngSample.shannon.uniqueBytes, '/ 256');
console.log('Chi-Square Statistic χ²  :', csprngSample.chiSquare.chiSquareStat.toFixed(2));
console.log('Chi-Square p-value       :', csprngSample.chiSquare.pValue.toFixed(6));
console.log('NIST SP 800-22 Verdict   :', csprngSample.chiSquare.verdictMessage);
console.log('Bit Raster Samples       :', csprngSample.bitRaster.slice(0, 32).join(''), '...(first 32 bits)');

// ---------------------------------------------------------------------------
// 4. PASSWORD ENTROPY & STRENGTH ESTIMATION (CLASSICAL INFORMATION MODEL)
// ---------------------------------------------------------------------------
console.log('\n--- 4. Password Strength & Entropy Estimator Audit ---');
const pass1 = computePasswordEntropy('pass1234');
const pass2 = computePasswordEntropy('Tr0ub4dor&3');
const pass3 = computePasswordEntropy('correct horse battery staple');
const pass4 = computePasswordEntropy('eK9#mQ2$vL8*zP4!wR7^tY1@bN5&');

console.log('[Password #1: "pass1234"]');
console.log('  Length & Pool   :', pass1.passwordLength, 'chars | Pool |R| =', pass1.poolSize);
console.log('  Theoretical H   :', pass1.shannonEntropyBits, 'bits | Rating:', pass1.strengthCategory.toUpperCase());
console.log('  GPU Crack Time  :', pass1.crackTimes.offlineSingleGpu);

console.log('[Password #2: "Tr0ub4dor&3"] (Complex Short)');
console.log('  Length & Pool   :', pass2.passwordLength, 'chars | Pool |R| =', pass2.poolSize);
console.log('  Theoretical H   :', pass2.shannonEntropyBits, 'bits | Rating:', pass2.strengthCategory.toUpperCase());
console.log('  GPU Crack Time  :', pass2.crackTimes.offlineSingleGpu);

console.log('[Password #3: "correct horse battery staple"] (NIST Recommended Passphrase)');
console.log('  Length & Pool   :', pass3.passwordLength, 'chars | Pool |R| =', pass3.poolSize);
console.log('  Theoretical H   :', pass3.shannonEntropyBits, 'bits | Rating:', pass3.strengthCategory.toUpperCase());
console.log('  GPU Crack Time  :', pass3.crackTimes.offlineSingleGpu);

console.log('[Password #4: "eK9#mQ2$vL8*zP4!wR7^tY1@bN5&"] (Cryptographic Token)');
console.log('  Length & Pool   :', pass4.passwordLength, 'chars | Pool |R| =', pass4.poolSize);
console.log('  Theoretical H   :', pass4.shannonEntropyBits, 'bits | Rating:', pass4.strengthCategory.toUpperCase());
console.log('  GPU Crack Time  :', pass4.crackTimes.offlineSingleGpu);

console.log('\n=== AUDIT COMPLETE ===');
